"""Initial knowledge_base schema

Revision ID: d9f55ded3722
Revises: 
Create Date: 2026-02-23 03:12:58.163248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9f55ded3722'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_base',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PLANNED', 'PARSER_CREATION', 'PARSING', 'LOADING_TO_RAG', 'ACTUAL_VERSION', 'OUTDATED_VERSION', name='docstatus'), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('doc_type', sa.String(), nullable=False),
    sa.Column('notebooklm_id', sa.String(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('local_path', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_base_name'), 'knowledge_base', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_base_name'), table_name='knowledge_base')
    op.drop_table('knowledge_base')
    # ### end Alembic commands ###
